#!/bin/sh
# startsyslog - Start syslogd and show logging messages
# (C) Klaus Knopper Jun 2001

PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

TITLE="SYSLOG"

RXVT=""
[ -n "$DISPLAY" ] && RXVT="x-terminal-emulator -T $TITLE -bg black -fg green  -e"
[ "`id -u`" != "0" ] && exec $RXVT su-me "$0" "$@"

[ -x /etc/init.d/sysklogd ] && /etc/init.d/sysklogd start

tail -f /var/log/syslog

exit 0

