#!/bin/sh
# startsyslog - Start syslogd and show logging messages
# (C) Klaus Knopper Jun 2001
# (C) 2007  Kel Modderman <kel@otaku42.de>

PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

[ "$(id -u)" -eq 0 ] || exec su-me "$0" "$@"

if [ ! -x /etc/init.d/sysklogd ]; then
	echo "syslogd not installed, aborting."
	exit 1
fi

if invoke-rc.d sysklogd reload-or-restart; then
	tail -f /var/log/syslog
else
	echo "syslogd failed to start, aborting."
	exit 2
fi

exit 0
